version: '3.1'
services:
  
  order:
    build: .
    command: "npm run start:dev"
    environment:
      PORT: 8003
    volumes:
      - .:/order
    ports:
      - "8003:8003"
       # Port required for debugging with node
      - "9226:9226"

  
 
volumes:
  db: {}
 