version: '3.1'
services:
  
  cart:
    build: .
    command: "npm run start:dev"
    environment:
      PORT: 8002
    volumes:
      - .:/cart
    ports:
      - "8002:8002"
       # Port required for debugging with node
      - "9227:9227"

  
 
volumes:
  db: {}
 